name: front_flutter
description: Mobile frontend part for PawGuider application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: 7.7.0
  fluentui_icons: ^1.0.0
  gap: ^3.0.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.0.0
  provider: ^6.0.5
  flutter_session_manager: ^1.0.3
  image_picker: ^1.0.4
  http: ^1.1.0
  path_provider: ^2.1.1
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/